export var brands = [
    "Acura",
    "Alfa Romeo",
    "Aston Martin",
    "Audi",
    "Bentley",
    "BMW",
    "Bugatti",
    "Buick",
    "Cadillac",
    "Chevrolet",
    "Chrysler",
    "Citroen",
    "Dodge",
    "Ferrari",
    "Fiat",
    "Ford",
    "Geely",
    "General Motors",
    "GMC",
    "Honda",
    "Hyundai",
    "Infiniti",
    "Jaguar",
    "Jeep",
    "Kia",
    "Koenigsegg",
    "Koenigsegg",
    "Lamborghini",
    "Land Rover",
    "Lexus",
    "Maserati",
    "Mazda",
    "McLaren",
    "Mercedes-Benz",
    "Mini",
    "Mitsubishi",
    "Nissan",
    "Pagani",
    "Pagani",
    "Peugeot",
    "Porsche",
    "Ram",
    "Renault",
    "Rolls Royce",
    "Saab",
    "Saab",
    "Subaru",
    "Suzuki",
    "TATA Motors",
    "Tata Motors",
    "Tesla",
    "Toyota",
    "Volkswagen",
    "Volvo"
]

export var fuel=[
    "CNG",
    "Diesel",
    "Hybrid",
    "LPG",
    "Petrol"
]

export var cities=[
    "Abbotabad",
    "Ahmedpur East",
    "Arif Wala",
    "Attock",
    "Badin",
    "Bahawalnagar",
    "Bahawalpur",
    "Bhakkar",
    "Bhalwal",
    "Burewala",
    "Chakwal",
    "Chaman",
    "Charsadda",
    "Chiniot",
    "Chishtian",
    "Dadu",
    "Daharki",
    "Daska",
    "Dera Ghazi Khan",
    "Dera Ismail Khan",
    "Faisalabad",
    "Ferozwala",
    "Ghotki",
    "Gojra",
    "Gujranwala",
    "Gujranwala Cantonment",
    "Gujrat",
    "Hafizabad",
    "Haroonabad",
    "Hasilpur",
    "Hub",
    "Hyderabad",
    "Islamabad",
    "Jacobabad",
    "Jaranwala",
    "Jatoi",
    "Jhang",
    "Jhelum",
    "Kabal",
    "Kamalia",
    "Kamber Ali Khan",
    "Kāmoke",
    "Kandhkot",
    "Karachi",
    "Kasur",
    "Khairpur",
    "Khanewal",
    "Khanpur",
    "Khushab",
    "Khuzdar",
    "Kohat",
    "Kot Abdul Malik",
    "Kot Addu",
    "Kotri",
    "Lahore",
    "Larkana",
    "Layyah",
    "Lodhran",
    "Mandi Bahauddin",
    "Mansehra",
    "Mardan",
    "Mianwali",
    "Mingora",
    "Mirpur",
    "Mirpur Khas",
    "Mirpur Mathelo",
    "Multan",
    "Muridke",
    "Muzaffarabad",
    "Muzaffargarh",
    "Narowal",
    "Nawabshah",
    "Nowshera",
    "Okara",
    "Pakpattan",
    "Peshawar",
    "Quetta",
    "Rahim Yar Khan",
    "Rawalpindi",
    "Sadiqabad",
    "Sahiwal",
    "Sambrial",
    "Samundri",
    "Sargodha",
    "Shahdadkot",
    "Sheikhupura",
    "Shikarpur",
    "Sialkot",
    "Sukkur",
    "Swabi",
    "Tando Adam",
    "Tando Allahyar",
    "Tando Muhammad Khan",
    "Taxila",
    "Turbat",
    "Umerkot",
    "Vehari",
    "Wah Cantonment",
    "Wazirabad",
]